version: '3.3'

services:
  vault:
    image: vault
    restart: "no"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${ROOTTOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports:
      - "1234:1234"
    networks:
      - internal

networks:
  internal:
    name: internal